/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;


import java.util.ArrayList;
import java.util.List;
import Entidades.Multa;

/**
 *
 * @author @author Jomayra Larico
 */
public class JFrameHistorialMultas extends javax.swing.JFrame {
    
    Dueño dueño;
    List<Multa> multas = new ArrayList<>();
    
    /**
     * Creates new form JFrameHistorialMultas
     */
    public JFrameHistorialMultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMultas = new javax.swing.JTable();
        btnGenerar = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        lblTextoFondoMulta = new javax.swing.JLabel();
        lblTextoFondoMes1 = new javax.swing.JLabel();
        lblTextoFondoMes2 = new javax.swing.JLabel();
        lblTextoFondoMes3 = new javax.swing.JLabel();
        lblTextoFondoMes4 = new javax.swing.JLabel();
        lblDescripcionFondoMes1 = new javax.swing.JLabel();
        lblDescripcionFondoMes2 = new javax.swing.JLabel();
        lblDescripcionFondoMes3 = new javax.swing.JLabel();
        lblDescripcionFondoMes4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitulo.setText("Historial de Multas");

        tbMultas.setBackground(new java.awt.Color(204, 204, 204));
        tbMultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código de Cliente", "Monto Multa", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbMultas);

        btnGenerar.setBackground(new java.awt.Color(0, 0, 0));
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setText("Generar Multa");

        btnPagar.setBackground(new java.awt.Color(0, 0, 0));
        btnPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnPagar.setText("Pagar Multa");

        btnActualizar.setBackground(new java.awt.Color(0, 0, 0));
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");

        lblTextoFondoMulta.setText("Los fondos recaudados por la multa, se utilizaran en:");

        lblTextoFondoMes1.setText("Mayo:");

        lblTextoFondoMes2.setText("Junio:");

        lblTextoFondoMes3.setText("Julio:");

        lblTextoFondoMes4.setText("Agosto:");

        lblDescripcionFondoMes1.setText("Campaña de vacunación");

        lblDescripcionFondoMes2.setText("Refugio de mascotas abandonadas");

        lblDescripcionFondoMes3.setText("Campaña de desparacitación");

        lblDescripcionFondoMes4.setText("Campaña de estirilización");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(lblTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTextoFondoMes1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblTextoFondoMes2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblTextoFondoMes3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblTextoFondoMes4, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDescripcionFondoMes4)
                                            .addComponent(lblDescripcionFondoMes3)
                                            .addComponent(lblDescripcionFondoMes2)
                                            .addComponent(lblDescripcionFondoMes1)))
                                    .addComponent(lblTextoFondoMulta))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnGenerar)
                        .addGap(18, 18, 18)
                        .addComponent(btnPagar)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTextoFondoMulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTextoFondoMes1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTextoFondoMes2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTextoFondoMes3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTextoFondoMes4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescripcionFondoMes1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDescripcionFondoMes2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDescripcionFondoMes3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDescripcionFondoMes4)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void llenarNombreMeses(){
        
    }
    
    public void llenarDescripcionMeses(){
        
    }
    
    public void actualizar(){
        
    }
    
    public void salir(){
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescripcionFondoMes1;
    private javax.swing.JLabel lblDescripcionFondoMes2;
    private javax.swing.JLabel lblDescripcionFondoMes3;
    private javax.swing.JLabel lblDescripcionFondoMes4;
    private javax.swing.JLabel lblTextoFondoMes1;
    private javax.swing.JLabel lblTextoFondoMes2;
    private javax.swing.JLabel lblTextoFondoMes3;
    private javax.swing.JLabel lblTextoFondoMes4;
    private javax.swing.JLabel lblTextoFondoMulta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tbMultas;
    // End of variables declaration//GEN-END:variables
}
